name: 'Silex: Unit test'

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    paths:
      - '**.php'
      - 'composer.json'
      - '.github/workflows/**'
    branches:
      - 'master'
  pull_request_target:
    paths:
      - 'libs/Social/**'
      - '.github/workflows/libs_social.yml'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@master
        with:
          php-version: '7.4'
          coverage: none
      - name: 'Composer: Installing'
        run: composer install
      - name: 'PHPUnit: Testing'
        run: vendor/bin/simple-phpunit
